### ISSUE TITLE
Authorization may raise `struct.error` in case of invalid secret

### ISSUE THREAD

**Issue by kevinboulain** [ansible/tacacs_plus#24]
As opposed to authentication.

Is this a mistake or should the docstring be updated to reflect it?
This may be a corner case because the application should surely authenticate before authorizing.

Example:
```python
from __future__ import print_function
import tacacs_plus.client

c = tacacs_plus.client.TACACSClient('tacacs', 49, 'invalid_secret')
print(c.authenticate('test', 'bla').valid) # False
print(c.authorize('test').valid) # raise
```

Will result in:
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    print(c.authorize('test').valid)
  File ".../tacacs_plus/client.py", line 246, in authorize
    reply = TACACSAuthorizationReply.unpacked(packet.body)
  File ".../tacacs_plus/authorization.py", line 130, in unpacked
    ) if arg_cnt else []
struct.error: unpack requires a bytes object of length 139
```

Regards.

**Comment by crisidev** [comment]
Yep, you are right. I can work on a PR to fix this bug sooner of later.
