### ISSUE TITLE
No handlers could be found for logger "__main__"

### ISSUE THREAD

**Issue by joegig** [ansible/tacacs_plus#44]
I am using tacacs_plus-2.6 and Python 2.7.5 and get above handlers error when running:
python tacacs_client -u TACACS-ADTestUser1 -H <IP Address> -k <KEY Name> -v authenticate -p <Password>

If I add the following to   def main():
    logging.basicConfig(level=logging.INFO)
    logging.info('Started')
    logging.info('Finished')

I get error regarding timed out

INFO:root:Started
INFO:root:Finished
ERROR:__main__:error: timed out
Traceback (most recent call last):
  File "tacacs_client", line 170, in main
    sys.exit(authenticate(cli, args))
  File "tacacs_client", line 119, in authenticate
    port=args.virtual_port)
  File "/usr/lib/python2.7/site-packages/tacacs_plus/client.py", line 199, in authenticate
    with self.closing():
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/tacacs_plus/client.py", line 81, in closing
    self.sock
  File "/usr/lib/python2.7/site-packages/tacacs_plus/client.py", line 75, in sock
    self._sock.connect(conn)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

**Comment by ryanpetrello** [comment]
@joegig sounds like a good candidate for a PR!
